### PR TITLE
fix(reporter): don't override windows icons if previously set

### LINKED ISSUE #56: regression: 'prefixes' are ignored on windows
see https://github.com/mlex/karma-spec-reporter/commit/3d511a367075b9142f3ede0d1eaa4b4fecc50e2f#commitcomment-17516766

### PR DESCRIPTION
**Pull request by tmcgee123**
Closes #56 

This will potentially fail due to coverage, I need to add more tests since overall coverage is being reduced  due to refactoring.

### CODE REVIEW

**Comment by tmcgee123** [comment]
@kayhadrin can you pull this down and verify it's working as intended?

**Comment by kayhadrin** [comment]
Ok, I'll try this at work tomorrow!

**Comment by kayhadrin** [comment]
Hi @tmcgee123,
I tested it at work and it worked fine for me.

Example of my config in Karma:

```js
specReporter: {
    suppressSkipped: true, // do not print information about skipped tests
    showSpecTiming: true, // print the time elapsed for each spec
    prefixes: {
        success: '[P] ',
        failure: '[F] ',
        pending: '* '
    }
},
```

**Comment by tmcgee123** [comment]
Closing a #64 fixes this

**Pull request closed without merging**
